version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/themes/advanced/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/themes/amaranth/"
    schedule:
      interval: "monthly"
