name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: [main]
    types: [completed]

jobs:
  netlify-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install
      - run: yarn build
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          deploy-message: Automated CD deploy
          publish-dir: ./public
          github-token: ${{ secrets.GITHUB_PAT }}
          github-deployment-environment: Netlify Deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
